Added env section with USER_AGENT_NAME and USER_AGENT_VERSION
razee-io/razeedeploy-delta pull request #225
Opened 2021-03-23 20:34 UTC by DeepaliAloori

https://github.com/razee-io/Razee/issues/142

2021-03-24 13:35 UTC, alewitt2 commented on kubernetes/job/resource.yaml
> +          value:  "{{{TRAVIS_TAG}}}"
```suggestion
        env:
          - name: USER_AGENT_NAME
            value:  razee-io/razeedeploy-delta
          - name: USER_AGENT_VERSION
            value:  "{{{TRAVIS_TAG}}}"
        command: ["./bin/razeedeploy-delta", "{{ COMMAND }}", "--namespace={{{ NAMESPACE }}}"]
        args: {{ ARGS_ARRAY }}
        # see README.md for args options. https://github.com/razee-io/razeedeploy-delta/blob/master/README.md
```

2021-03-24 13:37 UTC, alewitt2 requested changes
can you also add this change to https://github.com/razee-io/razeedeploy-delta/blob/master/kubernetes/razeedeploy-delta/resource.yaml#L125

2021-03-24 20:06 UTC, DeepaliAloori commented
> can you also add this change to https://github.com/razee-io/razeedeploy-delta/blob/master/kubernetes/razeedeploy-delta/resource.yaml#L125

 
Added the changes and opened a PR

2021-03-24 21:10 UTC, alewitt2 commented on kubernetes/job/resource.yaml
> +       - name: "razeedeploy-job{{{ UUID }}}"
```suggestion
      - name: "razeedeploy-job{{{ UUID }}}"
```

2021-03-24 21:11 UTC, alewitt2 commented on kubernetes/job/resource.yaml
> +       command: ["./bin/razeedeploy-delta", "{{ COMMAND }}", "--namespace={{{ NAMESPACE }}}"]
```suggestion
        env:
          - name: USER_AGENT_NAME
            value: razee.io/razeedeploy-delta
          - name: USER_AGENT_VERSION
            value: "{{{TRAVIS_TAG}}}"
        command: ["./bin/razeedeploy-delta", "{{ COMMAND }}", "--namespace={{{ NAMESPACE }}}"]
```

2021-03-24 21:11 UTC, alewitt2 commented on kubernetes/job/resource.yaml
> +        restartPolicy: Never
```suggestion
      restartPolicy: Never
```

2021-03-29 20:21 UTC, alewitt2 submitted a review, later dismissed

2021-03-29 20:25 UTC, alewitt2 approved these changes

2021-03-29 20:25 UTC, merged